{
 "title": "FlightTrack 0.2v",
 "description": "Real-Time Flight Monitoring Data and Dashboards",
 "time": { "from": "2022-05-04T01:00:00.000Z", "to": "2022-05-04T02:00:00.000Z" },
 "panels": [
  { "title": "Flight Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unauthorized Flight Zone",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT * from (SELECT\n  fr_a.callsign,\n  fr_a.latitude,\n  fr_a.longitude,\n  fr_a.velocity,\n  fr_a.last_contact\nFROM flight_records fr_a) as fr\nWHERE\n  $__unixEpochFilter(fr.last_contact)\n    and fr.latitude > '34.138560'::double precision\n  and fr.longitude > '-84.343549'::double precision\n  and fr.last_contact=(SELECT MAX(last_contact) FROM flight_records fr_b WHERE fr_b.callsign = fr.callsign)\nORDER BY fr.last_contact DESC"
    }
   ]
  },
  {
   "title": "Recent Flights Over Area",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT * from (SELECT case when company is NULL THEN 'UNKNOWN' else company END as \"company\", \n  fr.* from (SELECT\n  last_contact as \"time\",\n  callsign,\n  latitude,\n  longitude,\n  velocity,\n  geo_altitue as \"altitude (ft)\",\n  SUBSTRING(callsign,1,3) as three_letter_id\nFROM flight_records) as fr\nLEFT OUTER JOIN flight_call_signs fcs on fr.three_letter_id = fcs.three_letter_id\nWHERE\n  $__unixEpochFilter(time)\n  AND fr.time=(SELECT MAX(last_contact) FROM flight_records fr_b WHERE fr_b.callsign = fr.callsign)\n) records ORDER BY time desc"
    }
   ]
  },
  {
   "title": "Recent Flights",
   "type": "geomap",
   "description": "Current tracker of recent flight refreshed periodically.",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT * FROM (SELECT\n  fr_a.callsign,\n  fr_a.latitude,\n  fr_a.longitude,\n  fr_a.last_contact\nFROM flight_records fr_a\nWHERE\n  $__unixEpochFilter(fr_a.last_contact)\n  AND fr_a.last_contact=(SELECT MAX(last_contact) FROM flight_records fr_b WHERE fr_b.callsign = fr_a.callsign)) as records\nORDER BY records.last_contact DESC"
    }
   ]
  }
 ]
}