version: "3"
services:
  postgres-grafana:
    image: postgres:latest
    container_name: postgres-grafana
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "35432:5432"
    volumes:
      - ./postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  flight-track:
    image: default/flight-aggregator
    container_name: flight-track
    depends_on:
      - postgres-grafana

  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres-grafana
      - flight-track
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ORG_ROLE=viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=true